services:

  dmp:
    # image: ghcr.io/harelive/dst-management-platform-api:latest # 测试用
    image: ghcr.io/miracleeverywhere/dst-management-platform-api:latest
    container_name: dmp

    ports:
      - 9000:80
      - 10888:10888/udp # 多服务器模式下Master节点master_port端口，默认为10888
      - 10998:10998/udp
      - 10999:10999/udp
      - 11000:11000/udp
      - 11001:11001/udp
      - 27017:27017/udp # steam认证端口，udp和tcp都需要。默认为27017、8767，多服务器配置模式下默认为27018、8768和27019、8769
      - 27017:27017/tcp
      - 8767:8767/udp
      - 8767:8767/tcp
      - 27018:27018/udp
      - 27018:27018/tcp
      - 8768:8768/udp
      - 8768:8768/tcp
      - 27019:27019/udp
      - 27019:27019/tcp
      - 8769:8769/udp
      - 8769:8769/tcp

    # 新建一个文件夹存Dockerfile
    volumes:
      - ./.klei:/root/.klei
      - ./config:/root/config
    network_mode: bridge

    # restart: unless-stopped #选择是否开机自启
    environment:
      - TZ=Asia/Shanghai
      - PGID=$(id -g)
      - PUID=$(id -u)

